# Every test file has one or more tests...
test_name: Get some fake data from the JSON placeholder API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: Make sure we have the right ID

    # Define the request to be made...
    request:
      url: https://jsonplaceholder.typicode.com/posts/1
      method: GET

    # ...and the expected response code and body
    response:
      status_code: 200
      body:
        id: 1

test_name: some post

stages:
  - name: post something
    request:
      url: https://jsonplaceholder.typicode.com/posts
      json:
        title: "title"
        body: "bar"
        userId: 5
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 201
      body:
        userId: 5

